### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by arrrrr444** [susc/vercel-web-screenshot#1]
![Screenshot_2022-08-26-11-51-18](https://user-images.githubusercontent.com/77874962/186828309-ba9b5a67-daba-4450-b566-81b478cb2ab7.png)

![Screenshot_2022-08-26-11-57-38](https://user-images.githubusercontent.com/77874962/186828256-7edca2a5-7610-43a6-8eba-3f0f0d433988.png)

**Comment by ArdhiXs** [comment]
[https://screenshot-vercel2.vercel.app/api/screenshot?url=](https://screenshot-vercel2.vercel.app/api/screenshot?url=http://google.com)

**Comment by ArdhiXs** [comment]
[https://screenshot-vercel2.vercel.app/](https://screenshot-vercel2.vercel.app/)

**Comment by arrrrr444** [comment]
[https://screenshot-vercel2.vercel.app/](https://screenshot-vercel2.vercel.app/)

**Comment by arrrrr444** [comment]
[Error](https://screenshot-vercel2.vercel.app/api/screenshot?url=http://google.com)
